# Generated by Django 5.2.5 on 2025-10-31 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='PerfilDentista',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
