# Generated by Django 5.2.5 on 2025-09-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('procedimientos', models.TextField(blank=True, help_text='Lista de procedimientos, uno por línea.')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
