# Generated by Django 5.2.5 on 2025-11-08 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duracion_estimada', models.PositiveIntegerField(default=60, help_text='Duración en minutos', verbose_name='Duración (min)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('especialidad', models.CharField(blank=True, max_length=120, verbose_name='Especialidad')),
                ('licencia', models.CharField(blank=True, max_length=60, verbose_name='Número de Licencia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_dentista', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Login')),
            ],
            options={
                'verbose_name': 'Dentista',
                'verbose_name_plural': 'Dentistas',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio turno')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin turno')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='domain.dentista')),
            ],
            options={
                'verbose_name': 'Horario de Disponibilidad',
                'verbose_name_plural': 'Horarios de Disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('score_riesgo', models.FloatField(default=0.0, help_text='Probabilidad calculada de inasistencia', verbose_name='Score de Riesgo (IA)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Login')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Inicio de Cita')),
                ('fecha_hora_fin', models.DateTimeField(verbose_name='Fin de Cita')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada / Asistió'), ('CANCEL_PAC', 'Cancelada por Paciente'), ('CANCEL_DOC', 'Cancelada por Dentista'), ('NO_SHOW', 'No Asistió (Inasistencia)')], default='PENDIENTE', max_length=15, verbose_name='Estado Actual')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas/Diagnóstico')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda', to='domain.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='domain.paciente')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='domain.servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo en Consultorio'), ('MERCADOPAGO', 'MercadoPago Online'), ('TRANSFERENCIA', 'Transferencia Bancaria')], default='EFECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Pagado'), ('FALLIDO', 'Fallido/Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('mercadopago_id', models.CharField(blank=True, help_text='ID de transacción de MercadoPago', max_length=100, null=True, unique=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_relacionado', to='domain.cita')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
