# Generated by Django 5.2.5 on 2025-12-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_odontogramaentrada'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('dentista', 'dia_semana'), name='unique_horario_por_dia'),
        ),
    ]
