# Generated by Django 5.2.5 on 2025-11-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Estrellas (1-5)')),
                ('comentario', models.TextField(blank=True, verbose_name='Opinión del Paciente')),
                ('sentimiento_ia', models.CharField(choices=[('POS', 'Positivo 😊'), ('NEU', 'Neutral 😐'), ('NEG', 'Negativo 😡')], default='NEU', max_length=3, verbose_name='Análisis IA')),
                ('es_publico', models.BooleanField(default=False, verbose_name='Visible en Landing Page')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='domain.cita')),
            ],
            options={
                'verbose_name': 'Encuesta de Satisfacción',
                'verbose_name_plural': 'Encuestas de Satisfacción',
            },
        ),
    ]
