# Generated by Django 5.2.5 on 2025-10-13 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_paciente_alter_servicio_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='licencia',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrador_domain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentista_domain', to=settings.AUTH_USER_MODEL),
        ),
    ]
