# Generated by Django 5.2.5 on 2025-11-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_encuestasatisfaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada (General)'), ('CONF_PACIENTE', 'Confirmada por Paciente (Email)'), ('CONF_DENTISTA', 'Confirmada por Dentista'), ('COMPLETADA', 'Completada / Asistió'), ('CANCELADA', 'Cancelada General'), ('CANCEL_PAC', 'Cancelada por Paciente'), ('CANCEL_DOC', 'Cancelada por Dentista'), ('NO_SHOW', 'No Asistió (Falta)')], default='PENDIENTE', max_length=15, verbose_name='Estado Actual'),
        ),
    ]
