# Generated by Django 5.2.5 on 2025-12-02 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_horario_unique_horario_por_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='domain.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'numero')},
            },
        ),
    ]
