# Generated by Django 5.2.5 on 2025-11-11 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('NO_SHOW', 'Inasistencia (No-Show)'), ('CANCEL_TARDIA', 'Cancelación Tardia (<24h)')], max_length=20, verbose_name='Motivo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Recargo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('LIQUIDADA', 'Liquidada'), ('PERDONADA', 'Perdonada (Admin)')], default='PENDIENTE', max_length=20, verbose_name='Estado de Pago')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalizaciones', to='domain.cita', verbose_name='Cita Incumplida')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalizaciones', to='domain.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Penalización',
                'verbose_name_plural': 'Penalizaciones',
            },
        ),
    ]
