# Generated by Django 5.2.5 on 2025-12-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_diente'),
    ]

    operations = [
        migrations.AddField(
            model_name='diente',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
