# Generated by Django 5.2.5 on 2025-11-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_penalizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('canal', models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('PUSH', 'Notificación Push'), ('SMS', 'Mensaje SMS')], max_length=10, verbose_name='Canal de Envío')),
                ('tipo', models.CharField(choices=[('RECORDATORIO', 'Recordatorio de Cita'), ('CONFIRMACION', 'Confirmación de Cita'), ('CANCELACION', 'Cancelación de Cita'), ('PAGO', 'Confirmación de Pago'), ('PENALIZACION', 'Aviso de Penalización'), ('MARKETING', 'Promoción')], max_length=20, verbose_name='Tipo de Notificación')),
                ('enviada_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('contenido', models.TextField(blank=True, verbose_name='Contenido (o payload)')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída por el usuario')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='domain.cita', verbose_name='Cita Relacionada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-enviada_el'],
            },
        ),
    ]
