# Generated by Django 5.2.5 on 2025-11-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='veces_reprogramada',
            field=models.PositiveIntegerField(default=0, verbose_name='Veces modificada'),
        ),
    ]
