# Generated by Django 5.2.5 on 2025-11-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_cita_veces_reprogramada'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
