# Generated by Django 5.2.5 on 2025-12-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_dentista_direccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsoporte',
            options={'ordering': ['-created_at']},
        ),
    ]
