# Generated by Django 5.2.5 on 2025-11-17 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_paciente_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='notas',
        ),
        migrations.AddField(
            model_name='cita',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='ID del evento en Google Calendar para mantener la sincronización.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='domain.dentista'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('INASISTENCIA', 'Inasistencia')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='domain.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='domain.servicio'),
            preserve_default=False,
        ),
    ]
