# Generated by Django 5.2.5 on 2025-12-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_alter_ticketsoporte_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dentista', 'dia_semana', 'hora_inicio']},
        ),
        migrations.RemoveConstraint(
            model_name='horario',
            name='unique_horario_por_dia',
        ),
    ]
