# Generated by Django 5.2.5 on 2025-11-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0009_remove_cita_notas_cita_google_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='citas_adjuntos/', verbose_name='Archivo/Radiografía'),
        ),
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Clínicas'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='domain.dentista', verbose_name='Dentista'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('INASISTENCIA', 'Inasistencia'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_fin',
            field=models.DateTimeField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_inicio',
            field=models.DateTimeField(verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='ID del evento en Google Calendar.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='domain.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='domain.servicio', verbose_name='Servicio'),
        ),
    ]
