# Generated by Django 5.2.5 on 2025-11-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_cita_archivo_adjunto_cita_notas_alter_cita_dentista_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Corte')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cantidad_transacciones', models.PositiveIntegerField(default=0)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='domain.dentista')),
            ],
            options={
                'verbose_name': 'Corte de Caja',
                'verbose_name_plural': 'Cortes de Caja',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_incluidos', to='domain.cortecaja', verbose_name='Corte de Caja'),
        ),
    ]
