# Generated by Django 5.2.5 on 2025-12-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0010_alter_horario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
