# Generated by Django 5.2.5 on 2025-12-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='veces_reprogramada',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
