# Generated by Django 5.2.5 on 2025-11-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_alter_pago_options_cortecaja_pago_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='dentistas/', verbose_name='Foto de Perfil'),
        ),
    ]
