# Generated by Django 5.2.5 on 2025-11-27 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_dentista_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortecaja',
            name='dentista',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='corte',
        ),
        migrations.RemoveField(
            model_name='penalizacion',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='penalizacion',
            name='paciente',
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dentista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disponibilidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='encuestasatisfaccion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Encuesta de satisfacción', 'verbose_name_plural': 'Encuestas de satisfacción'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={},
        ),
        migrations.RemoveField(
            model_name='cita',
            name='google_event_id',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='veces_reprogramada',
        ),
        migrations.RemoveField(
            model_name='dentista',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='encuestasatisfaccion',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='encuestasatisfaccion',
            name='es_publico',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='score_riesgo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='mercadopago_id',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='domain.dentista'),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='metadata_ia',
            field=models.JSONField(blank=True, help_text='Detalles adicionales generados por la IA (scores, etiquetas, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='domain.paciente'),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='puntuacion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Escala 1–5 (5 = excelente)', null=True),
        ),
        migrations.AddField(
            model_name='encuestasatisfaccion',
            name='recomendaria',
            field=models.BooleanField(default=True, help_text='Si recomendaría el consultorio.'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='domain.dentista'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='domain.dentista'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='cita',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='citas/adjuntos/'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='domain.dentista'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('INASISTENCIA', 'Inasistencia')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='domain.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='domain.servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='especialidad',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='dentistas/fotos/'),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_dentista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='dentista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='domain.dentista'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuesta_satisfaccion', to='domain.cita'),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='sentimiento_ia',
            field=models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('neutro', 'Neutro'), ('negativo', 'Negativo')], help_text='Resultado del análisis de sentimiento automático.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='enviada_el',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('success', 'Éxito'), ('error', 'Error')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADOPAGO', 'MercadoPago')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion_estimada',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='CorteCaja',
        ),
        migrations.DeleteModel(
            name='Penalizacion',
        ),
    ]
