# Generated by Django 5.2.5 on 2025-12-05 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0013_cita_recordatorio_24h_enviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('MERCADOPAGO', 'MercadoPago'), ('MERCADOPAGO_FAKE', 'MercadoPago (fake)')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('telefono', ''), _negated=True), fields=('dentista', 'telefono'), name='uniq_paciente_telefono_por_dentista'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(models.Func(models.F('nombre'), function='LOWER'), models.F('dentista'), name='uniq_paciente_nombre_por_dentista_lower'),
        ),
    ]
