# Generated by Django 5.2.5 on 2025-12-05 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0014_alter_pago_metodo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paciente',
            name='uniq_paciente_telefono_por_dentista',
        ),
        migrations.RemoveConstraint(
            model_name='paciente',
            name='uniq_paciente_nombre_por_dentista_lower',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('dentista', 'telefono'), name='uniq_paciente_telefono_por_dentista'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('dentista', 'nombre'), name='uniq_paciente_nombre_por_dentista'),
        ),
    ]
