# Generated by Django 5.2.5 on 2025-12-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0015_remove_paciente_uniq_paciente_telefono_por_dentista_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['dentista', 'fecha', 'hora_inicio'], name='domain_cita_dentist_33b1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha'], name='domain_cita_pacient_e67924_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado', 'created_at'], name='domain_pago_estado_0e2c03_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo', 'estado'], name='domain_pago_metodo_745ca2_idx'),
        ),
    ]
