# Generated by Django 5.2.5 on 2025-11-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentista', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
