# Generated by Django 5.2.5 on 2025-11-25 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentista', '0002_delete_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del doctor', max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(default='Odontología General', max_length=100)),
                ('licencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula Profesional')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentista.dentista')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('antecedentes', models.TextField(blank=True, help_text='Alergias o enfermedades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentista.dentista')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('INASISTENCIA', 'No Show')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='citas_archivos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentista.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentista.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_relacionado', to='dentista.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada', models.IntegerField(default=30, help_text='Duración en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentista.dentista')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentista.servicio'),
        ),
    ]
